import os
import re
import json
import arxiv
import yaml
import logging
import argparse
import datetime
import subprocess
from types import SimpleNamespace
from urllib.parse import urlencode

import feedparser
import requests
from bs4 import BeautifulSoup

logging.basicConfig(format='[%(asctime)s %(levelname)s] %(message)s',
                    datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

base_url = "https://arxiv.paperswithcode.com/api/v0/papers/"
github_url = "https://api.github.com/search/repositories"
arxiv_url = "https://arxiv.org/"
request_timeout = 20
rss_url = "https://rss.arxiv.org/rss/cs.CV"
arxiv_search_url = "https://arxiv.org/search/"
user_agent = "nerf-arxiv-daily/1.0 (wangqian@nudt.edu.cn)"
code_lookup_available = True

def load_config(config_file:str) -> dict:
    '''
    config_file: input config file path
    return: a dict of configuration
    '''
    # make filters pretty
    def pretty_filters(**config) -> dict:
        keywords = dict()
        EXCAPE = '\"'
        QUOTA = '' # NO-USE
        OR = 'OR' # TODO
        def parse_filters(filters:list):
            ret = ''
            for idx in range(0,len(filters)):
                filter = filters[idx]
                if len(filter.split()) > 1:
                    ret += (EXCAPE + filter + EXCAPE)  
                else:
                    ret += (QUOTA + filter + QUOTA)   
                if idx != len(filters) - 1:
                    ret += OR
            return ret
        for k,v in config['keywords'].items():
            keywords[k] = parse_filters(v['filters'])
        return keywords
    with open(config_file,'r') as f:
        config = yaml.load(f,Loader=yaml.FullLoader) 
        config['kv'] = pretty_filters(**config)
        logging.info(f'config = {config}')
    return config 

def get_authors(authors, first_author = False):
    output = str()
    if first_author == False:
        output = ", ".join(str(author) for author in authors)
    else:
        output = authors[0]
    return output
def sort_papers(papers):
    output = dict()
    keys = list(papers.keys())
    keys.sort(reverse=True)
    for key in keys:
        output[key] = papers[key]
    return output    
def get_code_link(qword:str) -> str:
    """
    This short function was auto-generated by ChatGPT. 
    I only renamed some params and added some comments.
    @param qword: query string, eg. arxiv ids and paper titles
    @return paper_code in github: string, if not found, return None
    """
    # query = f"arxiv:{arxiv_id}"
    query = f"{qword}"
    params = {
        "q": query,
        "sort": "stars",
        "order": "desc"
    }
    r = requests.get(github_url, params=params, timeout=request_timeout)
    r.raise_for_status()
    results = r.json()
    code_link = None
    if results["total_count"] > 0:
        code_link = results["items"][0]["html_url"]
    return code_link

def get_rss_results(query:str, max_results:int):
    """Use arXiv's official cs.CV RSS feed when the search API is throttled."""
    response = requests.get(
        rss_url,
        timeout=request_timeout,
        headers={"User-Agent": user_agent},
    )
    response.raise_for_status()
    feed = feedparser.parse(response.content)
    if feed.bozo:
        raise ValueError(f"invalid arXiv RSS response: {feed.bozo_exception}")

    terms = [term.strip().strip('"').lower() for term in query.split("OR")]
    terms = [term for term in terms if term]
    results = []
    for entry in feed.entries:
        title = entry.get("title", "").replace("\n", " ").strip()
        summary = entry.get("summary", "").replace("\n", " ").strip()
        if terms and not any(term in f"{title} {summary}".lower() for term in terms):
            continue

        paper_url = entry.get("link", "")
        paper_id = paper_url.rstrip("/").rsplit("/", 1)[-1]
        author_names = [author.get("name", "") for author in entry.get("authors", [])]
        if not author_names and entry.get("author"):
            author_names = [entry.author]
        published = entry.get("published_parsed") or feed.feed.get("published_parsed")
        published_dt = (
            datetime.datetime(*published[:6]) if published else datetime.datetime.now()
        )
        results.append(SimpleNamespace(
            get_short_id=lambda paper_id=paper_id: paper_id,
            title=title,
            entry_id=paper_url,
            summary=summary,
            authors=author_names or ["Unknown"],
            primary_category="cs.CV",
            published=published_dt,
            updated=published_dt,
            comment=None,
        ))
        if len(results) >= max_results:
            break
    return results

def get_search_results(query:str, max_results:int):
    """Fetch recent papers from arXiv's official HTML search interface."""
    results = []
    if max_results <= 50:
        page_size = 50
    elif max_results <= 100:
        page_size = 100
    else:
        page_size = 200
    start = 0
    while len(results) < max_results:
        params = {
            "query": query,
            "searchtype": "all",
            "abstracts": "show",
            "order": "-announced_date_first",
            "size": page_size,
            "start": start,
        }
        try:
            response = requests.get(
                arxiv_search_url,
                params=params,
                timeout=30,
                headers={"User-Agent": user_agent},
            )
            response.raise_for_status()
            html = response.text
        except requests.RequestException as error:
            logging.warning(f"Python HTTP client failed ({error}); retrying with curl")
            try:
                completed = subprocess.run(
                    [
                        "curl", "--fail", "--location", "--silent", "--show-error",
                        "--max-time", "30", "--user-agent", user_agent,
                        f"{arxiv_search_url}?{urlencode(params)}",
                    ],
                    check=True,
                    capture_output=True,
                    text=True,
                    timeout=35,
                )
            except (OSError, subprocess.SubprocessError) as curl_error:
                raise RuntimeError(f"curl search fallback failed: {curl_error}") from curl_error
            html = completed.stdout
        soup = BeautifulSoup(html, "html.parser")
        items = soup.select("li.arxiv-result")
        if not items:
            break

        for item in items:
            link = item.select_one('p.list-title a[href*="/abs/"]')
            title_element = item.select_one("p.title")
            if link is None or title_element is None:
                continue
            paper_url = link.get("href", "")
            paper_id = paper_url.rstrip("/").rsplit("/", 1)[-1]
            authors = [author.get_text(" ", strip=True) for author in item.select("p.authors a")]
            abstract_element = item.select_one("span.abstract-full") or item.select_one("p.abstract")
            summary = abstract_element.get_text(" ", strip=True) if abstract_element else ""
            date_element = next(
                (element for element in item.select("p.is-size-7") if "Submitted" in element.get_text()),
                None,
            )
            date_match = re.search(
                r"Submitted\s+(\d{1,2}\s+\w+,\s+\d{4})",
                date_element.get_text(" ", strip=True) if date_element else "",
            )
            published_dt = (
                datetime.datetime.strptime(date_match.group(1), "%d %B, %Y")
                if date_match else datetime.datetime.now()
            )
            category = item.select_one("span.tag")
            results.append(SimpleNamespace(
                get_short_id=lambda paper_id=paper_id: paper_id,
                title=title_element.get_text(" ", strip=True),
                entry_id=paper_url,
                summary=summary,
                authors=authors or ["Unknown"],
                primary_category=category.get_text(strip=True) if category else "cs.CV",
                published=published_dt,
                updated=published_dt,
                comment=None,
            ))
            if len(results) >= max_results:
                break
        if len(items) < page_size:
            break
        start += len(items)
    return results
  
def get_daily_papers(topic,query="slam", max_results=2):
    """
    @param topic: str
    @param query: str
    @return paper_with_code: dict
    """
    # output 
    content = dict() 
    content_to_web = dict()
    search_engine = arxiv.Search(
        query = query,
        max_results = max_results,
        sort_by = arxiv.SortCriterion.SubmittedDate
    )

    try:
        results = get_search_results(query, max_results)
    except (requests.RequestException, ValueError, RuntimeError) as search_error:
        logging.warning(f"arXiv HTML search failed ({search_error}); trying the API")
        # arxiv 4.x removed Search.results(); Client.results() is the supported API.
        client = arxiv.Client(page_size=max_results)
        client._session.headers.update({"User-Agent": user_agent})
        try:
            results = list(client.results(search_engine))
        except arxiv.ArxivError as api_error:
            logging.warning(f"arXiv API failed ({api_error}); falling back to RSS")
            results = get_rss_results(query, max_results)

    for result in results:

        paper_id            = result.get_short_id()
        paper_title         = result.title
        paper_url           = result.entry_id
        code_url            = base_url + paper_id #TODO
        paper_abstract      = result.summary.replace("\n"," ")
        paper_authors       = get_authors(result.authors)
        paper_first_author  = get_authors(result.authors,first_author = True)
        primary_category    = result.primary_category
        publish_time        = result.published.date()
        update_time         = result.updated.date()
        comments            = result.comment

        logging.info(f"Time = {update_time} title = {paper_title} author = {paper_first_author}")

        # eg: 2108.09112v1 -> 2108.09112
        ver_pos = paper_id.find('v')
        if ver_pos == -1:
            paper_key = paper_id
        else:
            paper_key = paper_id[0:ver_pos]    
        paper_url = arxiv_url + 'abs/' + paper_key
        
        global code_lookup_available
        repo_url = None
        try:
            # Source-code metadata is optional; a lookup failure must not drop
            # an otherwise valid paper from the daily list.
            if code_lookup_available:
                response = requests.get(code_url, timeout=request_timeout)
                response.raise_for_status()
                r = response.json()
                if "official" in r and r["official"]:
                    repo_url = r["official"]["url"]
        except (requests.RequestException, ValueError, KeyError, TypeError) as e:
            logging.warning(f"code lookup failed: {e} with id: {paper_key}")
            code_lookup_available = False

        if repo_url is not None:
            content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|**[link]({})**|\n".format(
                   update_time,paper_title,paper_first_author,paper_key,paper_url,repo_url)
            content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({}), Code: **[{}]({})**".format(
                   update_time,paper_title,paper_first_author,paper_url,paper_url,repo_url,repo_url)
        else:
            content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|null|\n".format(
                   update_time,paper_title,paper_first_author,paper_key,paper_url)
            content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({})".format(
                   update_time,paper_title,paper_first_author,paper_url,paper_url)

        # TODO: select useful comments
        comments = None
        if comments is not None:
            content_to_web[paper_key] += f", {comments}\n"
        else:
            content_to_web[paper_key] += "\n"

    data = {topic:content}
    data_web = {topic:content_to_web}
    return data,data_web 

def update_paper_links(filename):
    '''
    weekly update paper links in json file 
    '''
    def parse_arxiv_string(s):
        parts = s.split("|")
        date = parts[1].strip()
        title = parts[2].strip()
        authors = parts[3].strip()
        arxiv_id = parts[4].strip()
        code = parts[5].strip()
        arxiv_id = re.sub(r'v\d+', '', arxiv_id)
        return date,title,authors,arxiv_id,code

    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)
            
        json_data = m.copy() 

        for keywords,v in json_data.items():
            logging.info(f'keywords = {keywords}')
            for paper_id,contents in v.items():
                contents = str(contents)

                update_time, paper_title, paper_first_author, paper_url, code_url = parse_arxiv_string(contents)

                contents = "|{}|{}|{}|{}|{}|\n".format(update_time,paper_title,paper_first_author,paper_url,code_url)
                json_data[keywords][paper_id] = str(contents)
                logging.info(f'paper_id = {paper_id}, contents = {contents}')
                
                valid_link = False if '|null|' in contents else True
                if valid_link:
                    continue
                try:
                    code_url = base_url + paper_id #TODO
                    response = requests.get(code_url, timeout=request_timeout)
                    response.raise_for_status()
                    r = response.json()
                    repo_url = None
                    if "official" in r and r["official"]:
                        repo_url = r["official"]["url"]
                        if repo_url is not None:
                            new_cont = contents.replace('|null|',f'|**[link]({repo_url})**|')
                            logging.info(f'ID = {paper_id}, contents = {new_cont}')
                            json_data[keywords][paper_id] = str(new_cont)

                except Exception as e:
                    logging.error(f"exception: {e} with id: {paper_id}")
        # dump to json file
        with open(filename,"w") as f:
            json.dump(json_data,f)

def update_json_file(filename,data_dict):
    '''
    daily update json file using data_dict
    '''
    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)
            
    json_data = m.copy() 
    
    # update papers in each keywords         
    for data in data_dict:
        for keyword in data.keys():
            papers = data[keyword]

            if keyword in json_data.keys():
                json_data[keyword].update(papers)
            else:
                json_data[keyword] = papers

    with open(filename,"w") as f:
        json.dump(json_data,f)
    
def json_to_md(filename,md_filename,
               task = '',
               to_web = False, 
               use_title = True, 
               use_tc = True,
               show_badge = True,
               use_b2t = True):
    """
    @param filename: str
    @param md_filename: str
    @return None
    """
    def pretty_math(s:str) -> str:
        ret = ''
        match = re.search(r"\$.*\$", s)
        if match == None:
            return s
        math_start,math_end = match.span()
        space_trail = space_leading = ''
        if s[:math_start][-1] != ' ' and '*' != s[:math_start][-1]: space_trail = ' ' 
        if s[math_end:][0] != ' ' and '*' != s[math_end:][0]: space_leading = ' ' 
        ret += s[:math_start] 
        ret += f'{space_trail}${match.group()[1:-1].strip()}${space_leading}' 
        ret += s[math_end:]
        return ret
  
    DateNow = datetime.date.today()
    DateNow = str(DateNow)
    DateNow = DateNow.replace('-','.')
    
    with open(filename,"r") as f:
        content = f.read()
        if not content:
            data = {}
        else:
            data = json.loads(content)

    # clean README.md if daily already exist else create it
    with open(md_filename,"w+") as f:
        pass

    # write data into README.md
    with open(md_filename,"a+") as f:

        if (use_title == True) and (to_web == True):
            f.write("---\n" + "layout: default\n" + "---\n\n")
        
        if show_badge == True:
            f.write(f"[![Contributors][contributors-shield]][contributors-url]\n")
            f.write(f"[![Forks][forks-shield]][forks-url]\n")
            f.write(f"[![Stargazers][stars-shield]][stars-url]\n")
            f.write(f"[![Issues][issues-shield]][issues-url]\n\n")    
                
        if use_title == True:
            #f.write(("<p align="center"><h1 align="center"><br><ins>CV-ARXIV-DAILY"
            #         "</ins><br>Automatically Update CV Papers Daily</h1></p>\n"))
            f.write("## Updated on " + DateNow + "\n")
        else:
            f.write("> Updated on " + DateNow + "\n")

        # TODO: add usage
        f.write("> Usage instructions: [here](./docs/README.md#usage)\n\n")

        #Add: table of contents
        if use_tc == True:
            f.write("<details>\n")
            f.write("  <summary>Table of Contents</summary>\n")
            f.write("  <ol>\n")
            for keyword in data.keys():
                day_content = data[keyword]
                if not day_content:
                    continue
                kw = keyword.replace(' ','-')      
                f.write(f"    <li><a href=#{kw.lower()}>{keyword}</a></li>\n")
            f.write("  </ol>\n")
            f.write("</details>\n\n")
        
        for keyword in data.keys():
            day_content = data[keyword]
            if not day_content:
                continue
            # the head of each part
            f.write(f"## {keyword}\n\n")

            if use_title == True :
                if to_web == False:
                    f.write("|Publish Date|Title|Authors|PDF|Code|\n" + "|---|---|---|---|---|\n")
                else:
                    f.write("| Publish Date | Title | Authors | PDF | Code |\n")
                    f.write("|:---------|:-----------------------|:---------|:------|:------|\n")

            # sort papers by date
            day_content = sort_papers(day_content)
        
            for _,v in day_content.items():
                if v is not None:
                    f.write(pretty_math(v)) # make latex pretty

            f.write(f"\n")
            
            #Add: back to top
            if use_b2t:
                top_info = f"#Updated on {DateNow}"
                top_info = top_info.replace(' ','-').replace('.','')
                f.write(f"<p align=right>(<a href={top_info.lower()}>back to top</a>)</p>\n\n")
                
            if show_badge == True:
                # we don't like long string, break it!
                f.write((f"[contributors-shield]: https://img.shields.io/github/"
                        f"contributors/AliTheFox86/nerf-arxiv-daily.svg?style=for-the-badge\n"))
                f.write((f"[contributors-url]: https://github.com/AliTheFox86/"
                        f"nerf-arxiv-daily/graphs/contributors\n"))
                f.write((f"[forks-shield]: https://img.shields.io/github/forks/AliTheFox86/"
                        f"nerf-arxiv-daily.svg?style=for-the-badge\n"))
                f.write((f"[forks-url]: https://github.com/AliTheFox86/"
                        f"nerf-arxiv-daily/network/members\n"))
                f.write((f"[stars-shield]: https://img.shields.io/github/stars/AliTheFox86/"
                        f"nerf-arxiv-daily.svg?style=for-the-badge\n"))
                f.write((f"[stars-url]: https://github.com/AliTheFox86/"
                        f"nerf-arxiv-daily/stargazers\n"))
                f.write((f"[issues-shield]: https://img.shields.io/github/issues/AliTheFox86/"
                        f"nerf-arxiv-daily.svg?style=for-the-badge\n"))
                f.write((f"[issues-url]: https://github.com/AliTheFox86/"
                        f"nerf-arxiv-daily/issues\n\n"))
                
    logging.info(f"{task} finished")        

def demo(**config):
    # TODO: use config
    data_collector = []
    data_collector_web= []
    
    keywords = config['kv']
    max_results = config['max_results']
    publish_readme = config['publish_readme']
    publish_gitpage = config['publish_gitpage']
    publish_wechat = config['publish_wechat']
    show_badge = config['show_badge']

    b_update = config['update_paper_links']
    logging.info(f'Update Paper Link = {b_update}')
    if config['update_paper_links'] == False:
        logging.info(f"GET daily papers begin")
        for topic, keyword in keywords.items():
            logging.info(f"Keyword: {topic}")
            data, data_web = get_daily_papers(topic, query = keyword,
                                            max_results = max_results)
            data_collector.append(data)
            data_collector_web.append(data_web)
            print("\n")
        logging.info(f"GET daily papers end")

    # 1. update README.md file
    if publish_readme:
        json_file = config['json_readme_path']
        md_file   = config['md_readme_path']
        # update paper links
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:    
            # update json data
            update_json_file(json_file,data_collector)
        # json data to markdown
        json_to_md(json_file,md_file, task ='Update Readme', \
            show_badge = show_badge)

    # 2. update docs/index.md file (to gitpage)
    #if publish_gitpage:
    #    json_file = config['json_gitpage_path']
    #    md_file   = config['md_gitpage_path']
    #    # TODO: duplicated update paper links!!!
    #    if config['update_paper_links']:
    #        update_paper_links(json_file)
    #    else:    
    #        update_json_file(json_file,data_collector)
    #   json_to_md(json_file, md_file, task ='Update GitPage', \
    #        to_web = True, show_badge = show_badge, \
    #        use_tc=False, use_b2t=False)

    # 3. Update docs/wechat.md file
    #if publish_wechat:
    #    json_file = config['json_wechat_path']
    #    md_file   = config['md_wechat_path']
    #    # TODO: duplicated update paper links!!!
    #    if config['update_paper_links']:
    #        update_paper_links(json_file)
    #    else:    
    #        update_json_file(json_file, data_collector_web)
    #    json_to_md(json_file, md_file, task ='Update Wechat', \
    #        to_web=False, use_title= False, show_badge = show_badge)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config_path',type=str, default='config.yaml',
                            help='configuration file path')
    parser.add_argument('--update_paper_links', default=False,
                        action="store_true",help='whether to update paper links etc.')
    parser.add_argument('--max_results', type=int,
                        help='override the configured number of search results')
    args = parser.parse_args()
    config = load_config(args.config_path)
    if args.max_results is not None:
        config['max_results'] = args.max_results
    config = {**config, 'update_paper_links':args.update_paper_links}
    demo(**config)
